#!/usr/bin/bash

CYAN='\033[1;36m'
NO_COLOR='\033[0m'
LABEL="db-setup"
printf "${CYAN}==== ${LABEL}${NO_COLOR}\n"

binn_path="$(realpath .)/binn"

echo $binn_path

source "$binn_path/db/drop"
source "$binn_path/db/create"
source "$binn_path/db/schema-load"
source "$binn_path/db/seed"
source "$binn_path/db/update_cognito_user_ids"
